# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2025 Ilya246
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 Whatstone
# SPDX-FileCopyrightText: 2025 significant harassment
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: pointOfInterest
  parent: BaseMobilePOI
  id: BasePOI
  abstract: true
  addComponents:
  - type: ForceAnchor

# Mono

- type: pointOfInterest
  id: BaseMobilePOI
  abstract: true
  minimumDistance: 4000 # Some sane defaults
  maximumDistance: 8000
  spawnGamePreset: [ NFAdventure, NFPirate, MonoStandard, MonoRogueTSF, MonoRogueUSSP, MonoTSFUSSP, MonoADS, MonoChimera, MonoMixed, MonoAllAtOnce ] # Behold my list of gamerules
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true
